### ISSUE TITLE
Couple bug's on Server Code/ Missing Files

### ISSUE THREAD

**Issue by luizoe** [hdneo/mxo-hd#1]
Hi there it's me luizoe the old guy from the forums that was trying to do the "Hardline teleport"(Maked the first version of Teleport) just a thing to Alexander and HD-Neo and John Kussack(Morpheus) i'm buildin on VC2013 and missing some csv files like World Objects csv and Somethings...so

the first error i got it is compiling....at "void loadAbilityDB(string path)"
you guys are using 
"
....
ability.setAbilityID(Convert.ToUInt16(data[0].ToString()));
ability.setGOID(Convert.ToInt32(data[1].ToString()));
ability.setAbilityName(data[2].ToString());
this.AbilityDB.Add(ability);
....
"
between the format that you get is example:"0\t-2154865\tAbilityName\tfalse"
a way to fix that is using the "string[] split = s.Split("\t".ToCharArray());" then attach instead "data[pos]" use "split[pos]"

Second error is loading "staticObjects.csv" this file was not uploaded or commited then provide it.

maybe is that all ^^
CYA i will be there looking and trying to add new features ^-^

**Comment by hdneo** [comment]
Hi luzio,
static objects file was too big for github. 
So you cann comment the loading from this file out in Dataloader.cs . 

The other files are in bin/debub/data - maybe you must copy them to your output directory (make a subdirectory "data").
The Abilitiy Table could be a little bit "buggy" as i was working on it before i commited.
It is a development release so no real support currently until we release a "stable" release. It was just to give the community the last develop code.

Btw. Alexander = HD_Neo = me ;)

**Comment by luizoe** [comment]
Hi Neo it's a long time right ^^
So did you have a Skype? then i will add you to contact about the things ^^
